; MIT licensed, see LICENSE.
;
; CBIOS for the sedna Z80 board.
;
; The only address baked in is the device enumeration window. Everything else (console, boot ROM
; latch, disk controllers) is discovered through that at boot, so the same ROM runs on any board
; that maps its devices anywhere.
;
; The system image lives on the reserved tracks of the boot disk, described by the boot descriptor
; sector (bootdef.inc). Cold boot is entered by the boot ROM with the boot controller's port in C
; and its unit in B; warm boot re-reads CCP+BDOS from that drive. The BIOS is deliberately not
; re-read: it holds the discovered port numbers, and reloading it would throw them away.
;
; `in r,(c)` / `out (c),r` put B on A8-A15, which the board's port map ignores.

	cpu	z80
	page	0

	include	"memmap.inc"
	include	"bootdef.inc"
	include	"wd1793.inc"

BDOSE	equ	BDOS+6		; the first six bytes of the BDOS image are its serial number

WBLEN	equ	BIOS-CCP	; CCP + BDOS only; the BIOS stays resident

IOBYTE	equ	0003h
CDISK	equ	0004h

; ---------------------------------------------------------------- device registers

LSRDR	equ	01h		; UART line status: data ready
LSRTHRE	equ	20h		; UART line status: transmit holding register empty

; Disk geometry comes from the same diskdefs file cpmtools formats the image with, so the DPB
; below cannot disagree with the medium. geometry.inc is generated by the Makefile.
	include	"geometry.inc"

SECSZ	equ	DSKLEN
SPT	equ	DSKSEC*DSKLEN/128	; a track holds this many CP/M records
NSEC	equ	WBLEN/DSKLEN	; sectors warm boot re-reads from the reserved tracks
NDRV	equ	4				; drive letters we are willing to hand out

	if	DSKBLS = 1024
BSH	equ	3
BLM	equ	7
	elseif	DSKBLS = 2048
BSH	equ	4
BLM	equ	15
	elseif	DSKBLS = 4096
BSH	equ	5
BLM	equ	31
	else
	error	"unsupported block size"
	endif

DSM	equ	(DSKTRK-DSKOFF)*DSKSEC*DSKLEN/DSKBLS-1
DRM	equ	DSKDIR-1
DIRBLK	equ	(DSKDIR*32+DSKBLS-1)/DSKBLS
CKS	equ	DSKDIR/4
ALVSZ	equ	DSM/8+1

; Allocation numbers are 8 bit up to 256 blocks and 16 bit above, which is what EXM encodes.
	if	DSM < 256
EXM	equ	DSKBLS/1024-1
	else
EXM	equ	DSKBLS/2048-1
	endif

	if	DIRBLK > 8
	error	"directory needs more than the eight blocks AL0 can name"
	endif
AL0	equ	(0FFh << (8-DIRBLK)) & 0FFh

	org	BIOS

	jp	BOOT
WBOOTE:	jp	WBOOT
	jp	CONST
	jp	CONIN
	jp	CONOUT
	jp	LIST
	jp	PUNCH
	jp	READER
	jp	HOME
	jp	SELDSK
	jp	SETTRK
	jp	SETSEC
	jp	SETDMA
	jp	READ
	jp	WRITE
	jp	LISTST
	jp	SECTRAN

	include	"devlib.inc"	; window layout and DEVFIND, shared with guest programs

; ---------------------------------------------------------------------- boot

BOOT:	di
	ld	sp,STACK
	ld	a,c		; the boot ROM passes the boot drive in C (port) and B (unit)
	ld	(BOOTP),a
	ld	a,b
	ld	(BOOTU),a
	call	DISCOVER
	ld	a,(LATCHP)	; drop the boot ROM; this code already runs above it
	ld	c,a
	xor	a
	out	(c),a
	ld	(IOBYTE),a
	ld	(CDISK),a
	jp	GOCPM

; Re-reads CCP+BDOS from the boot drive's reserved tracks. On error (typically the system disk
; was taken out) it says so once and retries, so putting the disk back resumes the boot.
WBOOT:	di
	ld	sp,STACK
	xor	a
	ld	(WBMSG),a
	ld	a,(BOOTP)
	ld	(FDCB),a
	ld	a,(BOOTU)
	ld	(FUNIT),a
; A readable but non-bootable disk would otherwise be loaded as if it held a system.
WBRD:	ld	hl,DIRBUF
	ld	(DMAADR),hl
	xor	a
	call	TSDIV
	call	READ
	or	a
	jr	nz,WBERR
	ld	a,(DIRBUF+BOFMAG)
	cp	BMAG0
	jr	nz,WBERR
	ld	a,(DIRBUF+BOFMAG+1)
	cp	BMAG1
	jr	nz,WBERR
	ld	a,BSYS0
	ld	(WBIDX),a
	ld	hl,CCP
	ld	(DMAADR),hl
	ld	a,NSEC
	ld	(WBCNT),a
WBRD1:	ld	a,(WBIDX)
	call	TSDIV
	call	READ
	or	a
	jr	nz,WBERR
	ld	hl,(DMAADR)
	ld	de,SECSZ
	add	hl,de
	ld	(DMAADR),hl
	ld	hl,WBIDX
	inc	(hl)
	ld	hl,WBCNT
	dec	(hl)
	jr	nz,WBRD1
	jr	GOCPM

WBERR:	ld	a,(WBMSG)
	or	a
	jr	nz,WBRD
	ld	a,1
	ld	(WBMSG),a
	ld	hl,WBSTR
	call	PUTS
	jr	WBRD

; Splits the linear sector index in A into the track and sector variables.
TSDIV:	ld	d,0
TSDIV1:	cp	DSKSEC
	jr	c,TSDIV2
	sub	DSKSEC
	inc	d
	jr	TSDIV1
TSDIV2:	ld	e,a
	ld	c,d
	ld	b,0
	ld	(TRACK),bc
	ld	c,e
	ld	(SECTOR),bc
	ret

GOCPM:	ld	a,0C3h
	ld	(0000h),a
	ld	hl,WBOOTE
	ld	(0001h),hl
	ld	(0005h),a
	ld	hl,BDOSE
	ld	(0006h),hl
	ld	a,3		; a TPA program may have left the divisor latch open
	call	UREG
	ld	a,3		; 8N1, DLAB clear
	out	(c),a
	ld	bc,0080h
	call	SETDMA
	ld	a,(CDISK)
	ld	c,a
	jp	CCP

; ------------------------------------------------------------------ discovery

DISCOVER:
	ld	c,CLSROM
	ld	b,0
	call	DEVFIND
	jr	c,NODEV
	ld	(LATCHP),a

	ld	c,CLSCHR
	ld	b,0
	call	DEVFIND
	jr	c,NODEV
	ld	(UARTB),a

	; Every block device becomes the next drive letter, in enumeration order. A controller with
	; several drives reports one entry per drive, distinguished by the unit in the attribute byte.
	ld	b,0
DISC1:	push	bc
	ld	c,CLSBLK
	call	DEVFIND
	pop	bc
	jr	c,DISC2
	ld	e,b
	ld	d,0
	ld	hl,DRVPRT
	add	hl,de
	ld	(hl),a		; controller port
	in	a,(BATT)
	and	0Fh		; low nibble selects the drive on that controller
	ld	hl,DRVUNI
	add	hl,de
	ld	(hl),a
	inc	b
	ld	a,b
	cp	NDRV
	jr	c,DISC1
DISC2:	ld	a,b
	ld	(DRVCNT),a
	; fall through: the drive booted from becomes A:

; Swaps the boot drive to the front of the drive table, so the disk the machine booted from is
; always A: no matter where its controller sits in enumeration order.
BOOTA:	ld	a,(DRVCNT)
	or	a
	ret	z
	ld	b,a
	ld	hl,DRVPRT
	ld	de,DRVUNI
BOOTA1:	ld	a,(BOOTP)
	cp	(hl)
	jr	nz,BOOTA2
	ld	a,(de)
	ld	c,a
	ld	a,(BOOTU)
	cp	c
	jr	z,BOOTA3
BOOTA2:	inc	hl
	inc	de
	djnz	BOOTA1
	ret			; boot drive beyond the lettered drives; leave the order alone
BOOTA3:	ld	a,(DRVPRT)
	ld	c,(hl)
	ld	(hl),a
	ld	a,c
	ld	(DRVPRT),a
	ld	a,(de)
	ld	c,a
	ld	a,(DRVUNI)
	ld	(de),a
	ld	a,c
	ld	(DRVUNI),a
	ret

; DEVFIND returns the device count in A when it fails, so storing it unchecked would leave the BIOS
; driving whatever sits at that port. Without a console or a way to unmap the ROM, stop instead.
NODEV:	di
	halt

; ------------------------------------------------------------------- console

; Returns the UART register at offset A in C.
UREG:	ld	hl,UARTB
	add	a,(hl)
	ld	c,a
	ret

CONST:	ld	a,5
	call	UREG
	in	a,(c)
	and	LSRDR
	ret	z
	ld	a,0FFh
	ret

CONIN:	ld	a,5
	call	UREG
CONI1:	in	a,(c)
	and	LSRDR
	jr	z,CONI1
	xor	a
	call	UREG
	in	a,(c)
	and	7Fh
	ret

CONOUT:	ld	b,c		; hold the character; C is about to become a port
	ld	a,5
	call	UREG
CONO1:	in	a,(c)
	and	LSRTHRE
	jr	z,CONO1
	xor	a
	call	UREG
	out	(c),b
	ret

LIST:	jp	CONOUT

; Prints the zero-terminated string at HL on the console.
PUTS:	ld	a,(hl)
	or	a
	ret	z
	push	hl
	ld	c,a
	call	CONOUT
	pop	hl
	inc	hl
	jr	PUTS

LISTST:	ld	a,0FFh		; LIST is the console, which is always ready
	ret

PUNCH:	ret

READER:	ld	a,1Ah
	ret

; ---------------------------------------------------------------------- disk

HOME:	ld	bc,0
SETTRK:	ld	(TRACK),bc
	ret

SETSEC:	ld	(SECTOR),bc
	ret

SETDMA:	ld	(DMAADR),bc
	ret

SECTRAN:			; no skew, so the logical sector is the physical one
	ld	h,b
	ld	l,c
	ret

SELDSK:	ld	a,(DRVCNT)
	cp	c
	jr	c,SELNONE	; drive letter past the last discovered device
	jr	z,SELNONE
	ld	a,c
	ld	(DRIVE),a

	ld	e,a		; latch the controller and unit this drive lives on
	ld	d,0
	ld	hl,DRVPRT
	add	hl,de
	ld	a,(hl)
	ld	(FDCB),a
	ld	hl,DRVUNI
	add	hl,de
	ld	a,(hl)
	ld	(FUNIT),a

	call	FSEL		; a drive with nothing in it is not an error, it is not selectable
	xor	a
	call	FREG
	in	a,(c)
	and	FNRDY
	jr	nz,SELNONE

	ld	a,(DRIVE)	; DPH = DPHS + drive * 16
	add	a,a
	add	a,a
	add	a,a
	add	a,a
	ld	e,a
	ld	d,0
	ld	hl,DPHS
	add	hl,de
	ret

SELNONE:
	ld	hl,0
	ret

; Returns the disk controller register at offset A in C.
FREG:	ld	hl,FDCB
	add	a,(hl)
	ld	c,a
	ret

; Waits for the controller to go idle, then returns its status register in A.
FWAIT:	xor	a
	call	FREG
FW1:	in	a,(c)
	bit	0,a		; FBUSY, tested without disturbing the status
	jr	nz,FW1
	ret

; A failed command leaves the data register holding whatever was last written to it, so without
; this check a read returns 128 copies of the track number and reports success.
IOSTAT:	call	FWAIT
	and	FERR
	ret	z
IOERR:	ld	a,1
	ret

; Selects the current drive on its controller, side 0.
FSEL:	ld	a,4
	call	FREG
	ld	a,(FUNIT)
	out	(c),a
	ret

; Exit Z on success, NZ if the controller reported an error.
SEEK:	call	FSEL
	ld	a,3
	call	FREG
	ld	a,(TRACK)
	out	(c),a
	xor	a
	call	FREG
	ld	a,FSEEK
	out	(c),a
	call	FWAIT
	and	FERRI
	ret	nz
	ld	a,2
	call	FREG
	ld	a,(SECTOR)
	inc	a		; the controller numbers sectors from one
	out	(c),a
	xor	a
	ret

READ:	call	SEEK
	jr	nz,IOERR
	xor	a
	call	FREG
	ld	a,FREAD
	out	(c),a
	ld	a,3
	call	FREG
	ld	hl,(DMAADR)
	ld	b,SECSZ
READ1:	in	a,(c)
	ld	(hl),a
	inc	hl
	djnz	READ1
	jp	IOSTAT

WRITE:	call	SEEK
	jr	nz,IOERR
	xor	a
	call	FREG
	ld	a,FWRITE
	out	(c),a
	ld	a,3
	call	FREG
	ld	hl,(DMAADR)
	ld	b,SECSZ
WRITE1:	ld	a,(hl)
	out	(c),a
	inc	hl
	djnz	WRITE1
	jp	IOSTAT

; ------------------------------------------------------------------ variables

LATCHP:	db	0		; boot ROM latch port
UARTB:	db	0		; console UART base port
FDCB:	db	0		; controller port of the selected drive
FUNIT:	db	0		; unit of the selected drive on that controller
DRIVE:	db	0
DRVCNT:	db	0
DRVPRT:	ds	NDRV
DRVUNI:	ds	NDRV

BOOTP:	db	0		; controller port of the drive booted from
BOOTU:	db	0		; unit of the drive booted from
WBIDX:	db	0		; warm boot: linear sector being read
WBCNT:	db	0		; warm boot: sectors left
WBMSG:	db	0		; warm boot: error already reported

WBSTR:	db	13,10,"INSERT SYSTEM DISK",13,10,0

TRACK:	dw	0
SECTOR:	dw	0
DMAADR:	dw	0080h

DPHS:
	dw	0,0,0,0,DIRBUF,DPB0,CSV0,ALV0
	dw	0,0,0,0,DIRBUF,DPB0,CSV1,ALV1
	dw	0,0,0,0,DIRBUF,DPB0,CSV2,ALV2
	dw	0,0,0,0,DIRBUF,DPB0,CSV3,ALV3

; Every discovered block device is assumed to carry the shipped floppy geometry; the window
; reports no media type yet.
DPB0:	dw	SPT
	db	BSH
	db	BLM
	db	EXM
	dw	DSM
	dw	DRM
	db	AL0
	db	0		; AL1, zero while the directory fits eight blocks
	dw	CKS
	dw	DSKOFF

DIRBUF:	ds	128
ALV0:	ds	ALVSZ
ALV1:	ds	ALVSZ
ALV2:	ds	ALVSZ
ALV3:	ds	ALVSZ
CSV0:	ds	CKS
CSV1:	ds	CKS
CSV2:	ds	CKS
CSV3:	ds	CKS

; SP wraps to FFFEh on the first push, so the stack grows down through the tail of the BIOS image.
; Only BOOT and WBOOT switch to it; every other entry point runs on the caller's stack.
STACK	equ	0
STKSZ	equ	128

	if	$ > MEMTOP-STKSZ
	error	"CBIOS overflows the BIOS region or its stack"
	endif

	end
